### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by MMaximus111** [denisenko93/Dommel.Bulk#1]
Hi! Your BulkInsert is very cool and fast method. Thank you so much!
Unfortunatelly, our infrastructure based on postgres. All our team waiting for new release with postgres support.

**Comment by denisenko93** [comment]
Method `BulkInsertParameters` supports all SQL dialects because it uses database parameters for providind values to database. Method `BulkInsert` uses type mappers for providing values to database. You can change type mappers for supports postgres using the `AddTypeMapper` method. In the future, I plan to add postgresql dialect support.

**Comment by MMaximus111** [comment]
Postgre support implemented. Close issue.
